In [2]:
#ND array

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
#0D array

arr = np.array(42)
print(arr)

42


In [4]:
#1D array

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
#2D array
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
#3D array
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
#Provides number of dimensions of the array

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [8]:
#Indexing

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr[0])

1


In [9]:
#Add wrt indices

import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2]+arr[3])

7


In [11]:
#Access 2D Array

import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
print('2nd element on 1sr row: ', arr[0, 1])

2nd element on 1sr row:  2


In [12]:
#Slicing an array
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
#Both start and end is mentioned
print(arr[1:5])
#Only end index is mentioned
print(arr[:5])
#Both start and end are not mentioned
print(arr[:])
#Only start index is mentioned
print(arr[4:])

[2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5 6 7]
[5 6 7]


In [13]:
#Negative Slicing

import numpy as np

arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [14]:
#Step

import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])
#every 2nd element from starting index will be printed

#Every other element(alternate)

print(arr[::2])

[2 4]
[1 3 5 7]


In [15]:
#Slicing 2D array

import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

#Row1 = 0, Row 2 = 1. Thus in row1, slicing takes place

[7 8 9]


In [16]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
element=arr[1,2]
#row,column, starting form 0.after row=1,only elements of row1 are checked.
print(element)

6


In [17]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
row_slice = arr[0:2, :] #[row sliced(row 0 and 1 sliced from rest of the array), column sliced(: means all columns)]
print(row_slice)

[[1 2 3]
 [4 5 6]]


In [18]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
col_slice = arr[:, 1:3]
print(col_slice)

[[2 3]
 [5 6]
 [8 9]]
